templates/loginform.php
www/loginform.php

Fix some encoding errors to strengthen security.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-259537461%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-259952001%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-269663807%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-274085404%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-274195344%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-274246827%22%2C%20%22https%3A//github. …

Multiple enhancements regarding correct encoding

---

lib/Auth/Source/privacyidea.php

<a href='https://www.codereviewhub.com/privacyidea/simplesamlphp-module-privacyidea/pull/25?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/25'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

add support for multi-value attributes

---

docs/privacyidea.txt
lib/Auth/Source/privacyidea.php

closes #32
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/cornelinux%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/34%23issuecomment-417655059%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-08-31T12%3A55%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Pull%20cde9fed4bc7732d0761bc615 …

Added detailmap to user attributes

---

dictionaries/privacyidea.definition.json
dictionaries/privacyidea.translation.json
docs/privacyidea.txt
lib/Auth/Process/privacyidea.php
lib/Auth/Process/serverconfig.php
lib/Auth/Process/tokenEnrollment.php
templates/loginform.php
themes/google/css/google.css
www/enrolltokenform.php
www/otpform.php

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/cornelinux%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/45%23issuecomment-448627541%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-12-19T15%3A07%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Pull%20a180a6f056d39cd551173b432116012450d …

Add token enrollment

---

lib/Auth/Process/tokenEnrollment.php
lib/Auth/utils.php

closes #48
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/49%23issuecomment-454740305%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/49%23issuecomment-454740305%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22looks%20good.%22%2C%20%22created_at%22%3A%20%222019-01-16T11%3A05%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/37443810%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/plettich%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img …

This fixes the GET params

---

dictionaries/privacyidea.definition.json
dictionaries/privacyidea.translation.json
lib/Auth/Process/privacyidea.php
lib/Auth/Source/privacyidea.php
templates/loginform.php
www/loginform.php
www/otpform.php

If a user has multiple u2f tokens. Only one can be used. This will fix it.
Thanks @jh23453 for the PR #22.
I had to write it down again, because we changed to much in the files and it had to be fixed in auth source and auth proc.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/50%23discussion_r248618867%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/50%23discussion_r248627570%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/50%23discussion_r248627665%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/50%23discussion_r248628794%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%203aa6ac1a65ae112166a1643b64e …

This fixes multi challenge for u2f

---

docs/privacyidea.txt
lib/Auth/Process/privacyidea.php
lib/Auth/Process/serverconfig.php
lib/Auth/Process/tokenEnrollment.php
lib/Auth/utils.php
templates/loginform.php
www/otpform.php

Trigger challenges are now enabled in auth proc filters.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/52%23discussion_r248699665%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%206b246304f1210194cd73d8bb8dc83c8056120ec6%20lib/Auth/Process/privacyidea.php%2013%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/52%23discussion_r248699665%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20am%20not%20sure%20if%20it%20is%20necessary%20to%20split%20the%20service%20accounts%20of%20enrollment%20and%20triggerchallenge.%5Cr%5CnHowever%2C%20in%20both%20cases%20it%20is%20a%20pi-serviceaccount%20for%20simplesaml%20and%20it%20has%20the%20necessary%20ri …

Added trigger challenge

---

dictionaries/privacyidea.definition.json
dictionaries/privacyidea.translation.json
docs/privacyidea.txt
lib/Auth/Process/privacyidea.php
lib/Auth/Process/tokenEnrollment.php
templates/loginform.php
www/js/u2f.js
www/otpform.php

The module privacyIDEA for simpleSAMLphp is now able to enroll u2f tokens in the authproc filter.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/53%23discussion_r249521443%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/53%23discussion_r252238485%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/53%23discussion_r252267126%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/commit/d577235211f6dac660170d7650e76e294777441b%23commitcomment-32118225%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/commit/d577235211f6dac660170d7650e76e294777441b%23commitcomment-32118235%22%2C%20%22h …

U2F token enrollment

---

Changelog

Version 1.8 2019-02-14
* Add pass on no token
* Add multiple uid keys
* Add triggerchallenge
* Fixed multi challenge
* Add token enrollment (totp, hotp and u2f)
* Add possibility to disable 2FA for special ip addresses
* Add option to disable 2FA
closes #54 
<a href='https://www.codereviewhub.com/privacyidea/simplesamlphp-module-privacyidea/pull/56?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/56'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
<a …

Added changes to changelog

---

themes/google/css/google.css

Button theme

---

lib/Auth/utils.php

The documentation added for utils.php
closes #61

Added documentation for utils.php

---

www/js/u2f-api.js
www/js/u2f.js

This makes it possible to use u2f with Firefox

Change u2f api version to v1.1

---

dictionaries/google.translation.json
dictionaries/privacyidea.translation.json

Dutch translation completed.
Also some minor spelling and translation mistakes corrected.
Added some clarification (OTP) to make it more clear what is meant in the interface

Dutch translation

---

templates/loginform.php
www/otpform.php

to ensure that users can logout and aren't locked, so they may be relogin with another user.
TODO: the styling could be enhanced

Add logout button to OTP site

---

lib/Auth/Process/checkClientIP.php
lib/Auth/Process/tokenEnrollment.php

uppercase class prefix to lowercase

---

docs/privacyidea.md
lib/Auth/Process/checkEntityID.php

add checkEntityID filter to ucs branch

checkEntityID authproc filter with all fixes

---

lib/Auth/Process/checkClientIP.php
lib/Auth/Process/tokenEnrollment.php

fix class prefix in ucs branch as done in #81

class prefix uppercase to lowercase

---

templates/loginform.php
www/otpform.php

add logout button from PR #90 to ucs branch

add logout button to 2FA loginform

---

lib/Auth/Process/privacyidea.php
www/otpform.php

add changes from #91 to ucs branch

ignore-passive-saml-requests PR #91 for ucs branch

---

templates/loginform.php

bring changes from #85 to ucs branch

fix escaping in loginform to prevent cross-site scripting in ucs branch

---

docs/privacyidea.md
lib/Auth/Process/privacyidea.php

remove SSO feature due to insecurity

---

lib/Auth/Process/privacyidea.php

This PR will add the realm as parameter to the triggerchallenge.
closes #115

respect realm in triggerchallenge

---

lib/Auth/Process/privacyidea.php

This resolves the last unresolved change from https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/111

move authenticationMethod to main process function

---

dictionaries/privacyidea.definition.json
templates/loginform.php
www/css/loginform.css
www/js/loginform.js

This would allow more strict Content Security Policy (disable `unsafe-inline`).

move inline JS and CSS to files, bug fixes

---

.gitmodules
composer.json
lib/Auth/Process/PrivacyideaAuthProc.php
lib/Auth/Source/AuthSourceLoginHandler.php
lib/Auth/Source/PrivacyideaAuthSource.php
lib/Auth/utils.php

This allows easier installation of this module with `composer require` without any extra work.

use composer and PSR-4 autoload instead of git submodule

---

templates/loginform.php
www/css/loginform.css

- add content to labels
- use labels for form fields only
Label text is accessible only to screen readers, so the visual part should be unchanged.
To be merged after https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/121

Labels fix

---

composer.json

fixes composer installation with minimum-stability: stable

chore(deps): use released version of PHP client

---

.gitmodules
Changelog
docs/privacyidea.md
lib/Auth/PILogger.php
lib/Auth/Process/PrivacyideaAuthProc.php
lib/Auth/Source/AuthSourceLoginHandler.php
lib/Auth/Source/PrivacyideaAuthSource.php
lib/Auth/utils.php
www/formbuilder.php

+ fix var_export warning
+ update changelog and docs

feature: preferred token type

---

.gitignore
templates/LoginForm.php
www/js/pi-webauthn.js

We will use composer for installation, so having the webauthn as submodule does not work anymore.

Add webauthn client

---

lib/Auth/PILogger.php
lib/Auth/Process/PrivacyideaAuthProc.php
lib/Auth/Source/PrivacyideaAuthSource.php
lib/Auth/Utils.php

because composer will be used to install

remove the ref to php-client

---

docs/privacyidea.md
lib/Auth/Source/PrivacyideaAuthSource.php
lib/Auth/Utils.php
templates/LoginForm.php
www/FormReceiver.php
www/css/loginform.css
www/js/loginform.js

- Additional OTP field on the first step of authentication to do the UI more readable for the user.
- Fix the problem with OTP field #144

152 add otpextra option

---

docs/privacyidea.md
templates/LoginForm.php

Check if data['pushAvailable'] exists at all before fetching the value.

Add nullcheck for pushAvailable

---

lib/Auth/Process/PrivacyideaAuthProc.php
lib/Auth/Source/PrivacyideaAuthSource.php
templates/LoginForm.php

Add the possibility to change the otp field hint in authproc

157 add the otp field hint to authproc

---

composer.json
docs/privacyidea.md
lib/Auth/PILogger.php
lib/Auth/Process/PrivacyideaAuthProc.php
lib/Auth/Source/PrivacyideaAuthSource.php
lib/Auth/Utils.php

- Update php-client
- Implement preferred client mode
- Translate to used modes
- Fix: preferred client mode (check if a value is valid)
- Update the docs
- Test

172 feature preferred client mode

---

docs/privacyidea.md
lib/Auth/Process/PrivacyideaAuthProc.php
lib/Auth/Utils.php

- Rename "tryFirstAuthentication" to "sendStaticPass" and use it as the authentication flow.
- Update the docs.
Closing #166

166 update authentication flow

---

lib/Auth/PILogger.php
lib/Auth/Process/PrivacyideaAuthProc.php
lib/Auth/Source/PrivacyideaAuthSource.php
lib/Auth/Utils.php
templates/LoginForm.php
www/FormBuilder.php
www/FormReceiver.php
www/css/loginform.css

- use the namespaces
- catch the exceptions
- add the type declarations
- rm unused elements and redundant assertions
- update the UI

177 upgrade the code

---

lib/Auth/Process/PrivacyideaAuthProc.php

Small fix to 'if' about the "authenticationFlow".

Update 'if' of the 'authenticationFlow' on PrivacyideaAuthProc.php

---

lib/Auth/Process/PrivacyideaAuthProc.php
lib/Auth/Source/PrivacyideaAuthSource.php
lib/Auth/Utils.php

add headers forwarding for authproc and authsource

86 feature forward headers

---

docs/privacyidea.md
lib/Auth/Process/PrivacyideaAuthProc.php
templates/LoginForm.php
www/FormBuilder.php

182 remove the old doenrolltoken function

---

docs/privacyidea.md
lib/Auth/Utils.php

replaced by preferred client mode

remove preferredTokenType config
