- lib/Auth/Source/privacyidea.php
Example injection would be a request to: www/loginform.php?pass=foo&transaction_id=none%26pass%3Dbar which would result in a request to the backend ?pass=foo&transaction_id=none&pass=bar.
> Fix parameter injection due to missing urlencoding.

- README.md
Adds a notice that TiQR is currently not supported by this plugin.
Fixes #8
<a href='https://www.codereviewhub.com/privacyidea/simplesamlphp-module-privacyidea/pull/9?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/9'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> README.md: TiQR not supported

- lib/Auth/Source/privacyidea.php
This removes the displaying of attributes after the user has logged in and fixes #11.
<a href='https://www.codereviewhub.com/privacyidea/simplesamlphp-module-privacyidea/pull/13?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/13'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Fix displaying of attributes during POST data screen

- docs/privacyidea.txt
- lib/Auth/Source/privacyidea.php
This allows to specify further attributes on the attributemap configuration. Only attributes configured here are added to the SAML response, all others are left untouched. Closes #12
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/14%23discussion_r94240347%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/14%23issuecomment-269791496%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/14%23discussion_r94251482%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/14%23discussion_r94270716%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/14%23discussion_r94271438%22%2C%20%22h …
> Add possibility to specify further attributes for SAML mapping

- lib/Auth/Source/privacyidea.php
In the log we got:
```
Jun 28 22:09:24 simplesamlphp ERROR [ad6c274e50] SimpleSAML_Error_Exception: Error 2 - Declaration of sspmod_privacyidea_Auth_Source_privacyidea::handleLogin($authStateId, $username, $password, $transaction_id, $signaturedata, $clientdata) should be compatible with sspmod_core_Auth_UserPassBase::handleLogin($authStateId, $username, $password)
```
After making the parameters $transaction_id, $signaturedata, and $clientdata optional the message is no longer logged.
<a href='https://www.codereviewhub.com/privacyidea/simplesamlphp-module-privacyidea/pull/20?approve=1'><img …
> handleLogin: make parameters optional

- dictionaries/privacyidea.translation.json
The text isn't displaying when english translations are defined in both translations and definitions. Addresses #26 and #27.  Tested with simplesamlphp 1.15.x
Before: 
After:
<a href='https://www.codereviewhub.com/privacyidea/simplesamlphp-module-privacyidea/pull/30?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/30'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Remove english translations to fix missing text on login page

- docs/privacyidea.txt
- lib/Auth/Source/privacyidea.php
closes #23 
Useful to get the full name in one line instead of separating sur and given name.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/35%23discussion_r215173998%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%2074160562014882e0d4f8293b98b15ac9d47fb1aa%20docs/privacyidea.txt%209%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/35%23discussion_r215173998%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cr%5Cn%40Mipronimo%20%20This%20is%20all%20perfect.%5Cr%5CnBut%20I%20am%20wondering%2C%20if%20we%20%28I%29%20have%20chosen%20a%20bad%20to%20remember%20configuration%20way%20in%20the%20first%20place.%5Cr%5Cn%5Cr%5CnIt%20felt%20more%20int …
> Added concatenation in mapping

- docs/privacyidea.txt
- lib/Auth/Process/privacyidea.php
This makes it possible for other authproc filters to disable privacyIDEA in simpleSAMLphp
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/43%23discussion_r241051828%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/43%23discussion_r241053484%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%209dd1a6160ae68780b700bc8a7c80ba3e5fd59065%20docs/privacyidea.txt%205%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/43%23discussion_r241053484%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Please%20be%20a%20bit%20more%20specific%20here%20in%20regards%20to%20%5C%22the%20path%20and%20the%20key%5C%22.%5Cr%5CnLike%20the%20p …
> Add enabled key

- lib/Auth/Process/privacyidea.php
- lib/Auth/Source/privacyidea.php
- templates/loginform.php
- www/otpform.php
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/47%23discussion_r245657291%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/47%23discussion_r245658193%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/47%23discussion_r245658774%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/47%23discussion_r245662626%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20cfc44f51d3dea5795e69f30d392c9804d98c7cb3%20lib/Auth/Process/privacyidea.php%2089%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/47%23discussion_r245657291%22%2C%20%22comments%22%3A%20%5B%7B%22body%22 …
> Fix U2F in auth proc filters

- www/otpform.php
The error code was only transmitted in case of challenge response.
This is fixed now.
<a href='https://www.codereviewhub.com/privacyidea/simplesamlphp-module-privacyidea/pull/51?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/51'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Fixed missing error messages

- docs/privacyidea.txt
- lib/Auth/Process/privacyidea.php
- lib/Auth/Process/serverconfig.php
This makes it possible to use either one or more uid keys. The first set one will be used.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/55%23discussion_r252265727%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/55%23discussion_r252267102%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/55%23discussion_r252267651%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/55%23discussion_r252285150%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20834e3742c3732ea59b84304176fbd650c53eac8a%20lib/Auth/Process/privacyidea.php%209%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/simplesamlphp-modul …
> Add multiple uid keys

- docs/privacyidea.txt
- lib/Auth/Process/privacyidea.php
- lib/Auth/Process/serverconfig.php
Now this plugin can try to authenticate before the user could enter a password.
If this is successful, the user will be passed without entering the otp.
closes #41
<a href='https://www.codereviewhub.com/privacyidea/simplesamlphp-module-privacyidea/pull/58?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/58'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> add pass on no token

- lib/Auth/Process/privacyidea.php
- www/otpform.php
When a passive SAML request (`<samlp:AuthnRequest IsPassive="true">`) is received a `urn:oasis:names:tc:SAML:2.0:status:NoPassive` status error is expected (instead of a login form).
The privacyidea plugin must not ask for a OTP in this case.
As a auth proc filter is executed after being authenticated we have to store that also the OTP authentication succeeded in the session (otherwise one can bypass OTP check (with passive requests, which are e.g. used by
Univention Corporate Server's Management Console) while one is not logged in)
> Fix passive requests in auth proc filter.

- lib/Auth/Process/privacyidea.php
This PR supresses warnings about missing keys in serverconfig by setting the according values if they are not present in the configuration file.
> set defaults to supress warnings about missing keys

- docs/privacyidea.md
- lib/Auth/Process/checkEntityID.php
closes #88
Compared to #87 
- removed the onmatch setting to always fallback to 2FA enabled if there is no match.
- a match with the regular expressions in "excludeattributes" sets the state variable to true, which will enable privacyIDEA although it should be disabled by entityid (therefore the name "exclude")
- use regular expression matching instead of exact matching
- useful debug messages
> checkEntityID authproc filter with regexp matching and fallback to 2FA enabled

- lib/Auth/Process/privacyidea.php
- lib/Auth/Process/serverconfig.php
Hello maintainers! Thanks for your work!
Commit 3f844871ef99deb0a407414af42f49d94d1cf320 adds lines
https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/e1e493171f5be00e9c2cff3944e1d2307c924e17/lib/Auth/Process/privacyidea.php#L33-L34
But these defaults break config merging in `sspmod_privacyidea_Auth_utils::buildServerconfig`
https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/e1e493171f5be00e9c2cff3944e1d2307c924e17/lib/Auth/utils.php#L199-L205
Because `tryFirstAuthentication` and `doTriggerChallenge` are keys of config of `privacyidea:serverconfig` auth proc filter and not `privacyidea:privacyidea` one. 
After the commit these `tryFirstAuthentication` and `doTriggerChallenge` keys are set in `$this->serverconfig` of …
> Fix auth proc filter config

- lib/Auth/Process/privacyidea.php
Hi there. I want to thank you for your work on this module.
I think there is a bug after refactor. But I could be wrong.
Here what I found:
Module calls authentication with incorrect password to check if `passOnNoToken` is enabled for user. If it's not enabled then module receives response with `wrong otp pin` message and throws exception.
https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/e1e493171f5be00e9c2cff3944e1d2307c924e17/lib/Auth/utils.php#L259
After commit bd101403fcec537b2d7cb4e3d44623fd90b962f2 there is no try/catch around `sspmod_privacyidea_Auth_utils::authenticate` call in `sspmod_privacyidea_Auth_Process_privacyidea::maybeTryFirstAuthentication`.
https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/e1e493171f5be00e9c2cff3944e1d2307c924e17/l …
> Fix pass on no token for auth proc filter

- lib/Auth/Process/PrivacyideaAuthProc.php
- lib/Auth/Source/PrivacyideaAuthSource.php
- lib/Auth/Utils.php
- templates/LoginForm.php
- www/FormReceiver.php
- www/css/loginform.css
* Wrap calls to the privacyidea client with try-catch so that exceptions that occur during the request (e.g. typo in server url) are caught and the error is shown
* Fix the order in which the username is received from the input form. Previously, the form entry was not the first in order which would cause a wrongly typed username to be used over and over again instead of using the new input
> catch connection exceptions

- lib/Auth/Source/PrivacyideaAuthSource.php
`in_array` checks whether a value exists in an array, i.e.
>>> in_array('foo',['foo'])
=> true
>>> in_array('foo',['foo' => 'bar'])
=> false
whereas `attributemap` and friends are array keys containing lists that
map PI attributes to SAML attributes.
Without this change, the plugin doesn't provide the mapped attributes
(i.e. `samlLoginName`, `surName` etc.), but the attributes returned from
PrivacyIDEA (i.e. `username`, `surname` etc.).
> Ensure that `attributemap` actually gets applied

- lib/Auth/Source/PrivacyideaAuthSource.php
In PHP you cannot dereference array-keys via `->`, so each field from `concatenationmap` was empty because of `$userAttributes->$item`.
cc @lukasmatusiewicz
> Fix property access on concatenation-map

- docs/privacyidea.md
- lib/Auth/Process/PrivacyideaAuthProc.php
Issue: [https://github.com/privacyidea/simplesamlphp-module-privacyidea/issues/161](https://github.com/privacyidea/simplesamlphp-module-privacyidea/issues/161)
- make doTriggerChallenge and tryFirstAuthentication in PrivacyideaAuthProc less dependent of each other.
This will allow to utilize both passOnNoToken (for users without enrolled tokens) and challenges (for users who have tokens) in the same process;
- update AuthProc options docs to be slightly more specific for related options;
> Fix Authproc doTriggerChallenge conflict with passOnNoToken

- .gitignore
- .gitmodules
- Changelog
- README.md
- composer.json
- docs/privacyidea.md
- lib/Auth/Process/PrivacyideaAuthProc.php
- lib/Auth/Source/PrivacyideaAuthSource.php
- lib/Auth/Utils.php
- templates/LoginForm.php
- www/FormBuilder.php
- www/FormReceiver.php
- www/js/loginform.js
- www/js/pi-webauthn.js
- www/js/u2f-api.js
+ Implement the authentication flows.
+ Update the authsource config template with an `authenticationFlow` option. Valid values are: `sendPass`, `triggerChallenge`, and `otpExtra`.
+ `doTriggerChallenge`, `doSendPassword` and `otpExtra` options are outdated and removed from the config template.
+  `authenticationFlow` is required. If the option isn't found or the value is invalid, the login mask contains per default: 1 username field and 1 pass field, and a proper error is written to the log.
+ Implement the `authenticationFlow` in `authproc`. Valid values: `default`, `triggerChallenge`.
+ rm submodule configuration and belonging files from the repo.
+ Fix: process token enrollment after trigger challenge if is set.
> Fix: otp extra & doSendPassword

- www/FormBuilder.php
Dear PrivacyIDEA support,
I think that the AuthProc Filter part is missing the username and this Pull Request adds it in the right way, I hope.
I can't get the username without it.
Best Regards,
Marco
> Added $username to AuthProc template data
